libraft no longer builds
       /home/curators/work/unpack-dir/unpacked/libraft-0.5.0.0-a19beb1f5e75c3d1982b78ae125ded3559712421062e39147eb5c9445c6472e7/src/Raft/Types.hs:71:42: error: [GHC-
39999]
           • No instance for ‘ConvertText ByteString [Char]’
               arising from a use of ‘toS’
           • In the second argument of ‘(.)’, namely ‘toS’
             In the first argument of ‘(<$>)’, namely
               ‘(intToNatural <=< readEither) . toS’
             In the expression: (intToNatural <=< readEither) . toS <$> mdata
          |
       71 |     case (intToNatural <=< readEither) . toS <$> mdata of
          |                                          ^^^