disable pontarius-xmpp since it now fails to build
cc @l29ah

Probably related to some recent library bump.

       Building library for pontarius-xmpp-0.5.7.0..
       [10 of 32] Compiling Network.Xmpp.Lens

       /home/curators/work/unpack-dir/unpacked/pontarius-xmpp-0.5.7.0-c350beab14dfe125b8ab22155145a9640b1cb00510c645f2c365d061d50a08
16/source/Network/Xmpp/Lens.hs:518:36: error: [GHC-76037]
           Not in scope: data constructor ‘ClientParams’
           |
       518 | clientServerIdentificationL inj cp@ClientParams{clientServerIdentification = x}
           |                                    ^^^^^^^^^^^^
:
       /home/curators/work/unpack-dir/unpacked/pontarius-xmpp-0.5.7.0-c350beab14dfe125b8ab22155145a9640b1cb00510c645f2c365d061d50a08
16/source/Network/Xmpp/Lens.hs:531:25: error: [GHC-76037]
           Not in scope: data constructor ‘Supported’
           |
       531 | supportedCiphersL inj s@Supported{supportedCiphers = x}
           |                         ^^^^^^^^^