Revert "try to re-enable regex-pcre2" (#7698)
This reverts commit 86fd6a6103ebf93e1ad13730fe968e9dbe4afbde.

Same error again unfortunately:

       Configuring regex-pcre2-1.0.0.0...
       Preprocessing library for regex-pcre2-1.0.0.0...
       compiling .stack-work/dist/x86_64-linux-tinfo6/ghc-9.12.2/build/Text/Regex/PCRE2/Wrap_hsc_make.c failed (exit code 1)
       rsp file was: ".stack-work/dist/x86_64-linux-tinfo6/ghc-9.12.2/build/Text/Regex/PCRE2/hsc2hscall293-0.rsp"
       command was: /usr/bin/gcc -c .stack-work/dist/x86_64-linux-tinfo6/ghc-9.12.2/build/Text/Regex/PCRE2/Wrap_hsc_make.c -o .stack-work/dist/x86_64-linux-tinfo6/ghc-9.12.2/build/Text/Regex/PCRE2/Wrap_hsc_make.o -fuse-ld=gold -Wl,--no-as-needed -D__GLASGOW_HASKELL__=912 -Dlinux_BUILD_OS=1 -Dx86_64_BUILD_ARCH=1 -Dlinux_HOST_OS=1 -Dx86_64_HOST_ARCH=1 -I/usr/include -I.stack-work/dist/x86_64-linux-tinfo6/ghc-9.12.2/build/autogen -I.stack-work/dist/x86_64-linux-tinfo6/ghc-9.12.2/build/global-autogen -include .stack-work/dist/x86_64-linux-tinfo6/ghc-9.12.2/build/autogen/cabal_macros.h -I/home/curators/.stack/programs/x86_64-linux/ghc-tinfo6-9.12.2/lib/ghc-9.12.2/lib/../lib/x86_64-linux-ghc-9.12.2-fcd3/bytestring-0.12.2.0-e583/include -I/home/curators/.stack/programs/x86_64-linux/ghc-tinfo6-9.12.2/lib/ghc-9.12.2/lib/../lib/x86_64-linux-ghc-9.12.2-fcd3/ghc-internal-9.1202.0-a797/include -I/home/curators/.stack/programs/x86_64-linux/ghc-tinfo6-9.12.2/lib/ghc-9.12.2/lib/../lib/x86_64-linux-ghc-9.12.2-fcd3/ghc-bignum-1.3-0ee7/include -I/home/curators/.stack/programs/x86_64-linux/ghc-tinfo6-9.12.2/lib/ghc-9.12.2/lib/../lib/x86_64-linux-ghc-9.12.2-fcd3/rts-1.0.2/include -I/home/curators/.stack/programs/x86_64-linux/ghc-tinfo6-9.12.2/include/include/
       error: In file included from .stack-work/dist/x86_64-linux-tinfo6/ghc-9.12.2/build/Text/Regex/PCRE2/Wrap_hsc_make.c:1:
       Wrap.hsc: In function ‘main’:
       /home/curators/work/unpack-dir/unpacked/regex-pcre2-1.0.0.0-35f856a636a323d3435a23954b357c6befb7a8d82b62b452a30c344b28f837b0/Wrap.hsc:369:84: error: ‘PCRE2_ALT_EXTENDED_CLASS’ undeclared (first use in this function)
       /home/curators/.stack/programs/x86_64-linux/ghc-tinfo6-9.12.2/lib/ghc-9.12.2/lib/template-hsc.h:112:10: note: in definition of macro ‘hsc_enum’
         112 |     if ((x) < 0)                                        \
             |          ^
:
: