allow tasty-papi testsuite to fail
       Test suite failure for package tasty-papi-0.1.2.0                                                        06:00:57 [12/968555]
           tasty-papi-run:  exited with: ExitFailure 1
       Full log available at /home/curators/work/unpack-dir/.stack-work/logs/tasty-papi-0.1.2.0-test.log

           All
             Fib
               6:                FAIL
                 Exception: PAPI: Failed to add counter TOT_INS: Permission level does not permit operation [-15]                                    CallStack (from HasCallStack):
                   error, called at ./Test/Tasty/PAPI.hs:267:9 in tasty-papi-0.1.2.0-3waaxibG1t4EaKKxpIkBOv:Test.Tasty.PAPI
:
:
             Misc
               IORef regression: FAIL
                 Exception: PAPI: Failed to add counter TOT_INS: Permission level does not permit operation [-15]
                 CallStack (from HasCallStack):
                   error, called at ./Test/Tasty/PAPI.hs:267:9 in tasty-papi-0.1.2.0-3waaxibG1t4EaKKxpIkBOv:Test.Tasty.PAPI

           8 out of 8 tests failed (0.00s)